source 'http://rubygems.org'

gem 'rails', '3.2.15'
gem 'pg', '0.14.1'
gem 'activerecord-import', '0.3.1', require: false
gem 'createsend', '3.1.0'
gem 'devise', '2.2.3'
gem 'jquery-rails', '3.0.4'
gem 'friendly_id', '4.0.9'
gem 'geocoder', '1.1.8'
gem 'sunspot_rails', '2.1.0'
gem 'rabl', git: 'git://github.com/nesquena/rabl.git'
gem 'oj', '2.0.14'
gem 'gon', '4.1.0'
gem 'kaminari', '0.14.1'
gem 'aws-sdk', '1.11.0'
gem 'uuidtools', '2.1.4'
gem 'faker', '1.1.2'
gem 'factory_girl_rails', '4.2.1'
gem 'newrelic_rpm', '3.6.5.130'
gem 'strong_parameters', '0.2.1'
gem 'inherited_resources', '1.4.0'
gem 'activerecord-postgres-hstore', '0.7.6'
gem 'ensure-encoding', '~> 0.1'
gem 'spreadsheet', '0.8.8'
gem 'twitter', '4.8.1'
gem 'delayed_job_active_record', '4.0.0'
gem 'daemons', '1.1.9'
gem 'workless'
gem 'rails-settings-cached', '0.2.4'
gem 'tinymce-rails', '~> 4.0.2'
gem 'rails3_before_render', '0.2.0'
gem 'public_activity', '1.4.0'
gem 'carrierwave', '0.9.0'
gem 'fog', '1.18.0'
gem 'unf'
gem 'unicorn', '4.6.3'
gem 'time_difference', '0.2.0'
gem 'wkhtmltopdf-binary', '0.9.9.1'
gem 'pdfkit', '0.5.4'
gem 'rmagick'
gem 'activerecord_any_of', '1.1'
gem 'draper', '~> 1.0'
gem 'seeker', '0.2.3'
gem 'bugsnag', '1.6.2'
gem 'seed_dump', '2.0.0'
gem 'progress_bar', '1.0.0'
gem 'slim', '2.0.2'
gem 'nokogiri', '1.6.0'
gem 'httparty', '0.12.0'
gem 'business_time'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'compass-rails', '1.0.3'
  gem 'uglifier', '2.3.0'
  gem 'backbone-on-rails', '0.9.10.0'
  gem 'marionette-rails', '1.1.0'
  gem 'i18n-js', '2.1.2'
  gem 'jquery-fileupload-rails', '0.4.1'
  gem 'simple_form', '2.1.0'
  gem 'nested_form', '0.3.2'
  gem 'turbo-sprockets-rails3', '0.3.9'
  gem 'select2-rails', '3.4.7'
  gem 'tilt', '~> 1.3.6'
  gem 'skim', '0.9.2'
  gem 'bootstrap-kaminari-views', '0.0.2'
end

group :development do
  gem 'quiet_assets', '1.0.2'
  gem 'rails-dev-tweaks'
  gem 'bullet', '4.5.0'
  gem 'sunspot_solr', '2.1.0'
  gem 'thin', '1.5.1'
  gem 'phrase', '0.4.14'
  gem 'hirb'
  gem 'heroku'
end

group :staging do
  gem 'phrase', '0.4.14'
end

group :test do
  gem 'rspec-rails', '2.14.1'
  gem 'rspec-html-matchers', '0.4.1'
  gem 'ci_reporter', '1.8.4'
  gem 'simplecov', '0.7.1', require: false
  gem 'simplecov-rcov', '0.2.3', require: false
  gem 'database_cleaner', '1.2.0'
  gem 'therubyracer', '0.12.0'
  gem 'sunspot_solr', '2.1.0'
  gem 'email_spec', '1.4.0'
  gem 'shoulda'
  gem 'launchy', '2.3.0'
  gem 'delorean', '2.1.0'
  gem 'capybara', '2.2.0'
  gem 'selenium-webdriver', '2.37.0'
  gem 'webmock', '1.16.0'
  gem 'codeclimate-test-reporter', require: nil
  gem 'spork-rails', '4.0.0'
end
